FROM maven:3.6-jdk-8 AS maven_build
LABEL maintainer "Jorge Herran"
WORKDIR /build
COPY /home/ec2-user/.m2/settings.xml /root/.m2/settings.xml
# Here maven relies on the copied settings.xml file
# RUN mvn package 