name: BuildStepTest

on:
  workflow_dispatch
jobs:
  laststepbuildtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume
      - name: baseimage-directory
        run: cd baseimage
      - uses: docker/build-push-action@v2
        with:
          tags: Dockermaven:local
          push: false
      - uses: jotahe/runactiondocker@main
        with:
          image: Dockermaven:local
          run: |
            echo "Executing last created docker maven image"
            docker run -it --rm -v ${{ github.workspace }}:/work