name: Test RunActionDocker

on:
  workflow_dispatch

jobs:
  version_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run docker action and set output for testing
        uses: ./
        id: run-docker
        with:
          image: docker:20.10.3
          run: |
            echo " This test the output version from the docker image" 
            echo "::set-output name=docker-version::`echo $DOCKER_VERSION`"
      - name: Test the output
        uses: actions/github-script@v3
        with:
          script: |
            const dockerVersion = '${{ steps.run-docker.outputs.docker-version }}';
            if (dockerVersion !== '20.10.3') {
              core.setFailed(`Output Test Failed`);
            }
  volume-mount-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create File to be mounted
        run: echo "some text" > someFile
      - name: Run docker action with mounted workspace
        uses: ./
        id: run-docker
        with:
          image: docker
          options: -v ${{ github.workspace }}:/work
          run: |
            echo " Testing the output from the mounted file"
            echo "::set-output name=file-contents::`cat /work/someFile`"
      - name: Check if file contents match
        uses: actions/github-script@v3
        with:
          script: |
            const fileContents = '${{ steps.run-docker.outputs.file-contents }}';
            if (fileContents !== 'some text') {
              core.setFailed(`Unable to mount workspace volume`);
            }