name: TestMountCase

on:
  workflow_dispatch
jobs:
  version_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume 
      - uses: jotahe/runactiondocker@main
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: gcr.io
          image: private-image:latest
          options: -v ${{ github.workspace }}:/work -e ABC=123
          run: |
            echo "Running Script"
            /work/run-script